[build]
  command = "npm run build"
  publish = ".next" 

[build.environment]
  NODE_ENV = "production"

# Cache configuration
[[build.caching]]
  directory = "/opt/buildhome/cache/.next/cache" 
[[build.caching]]
  directory = "/opt/buildhome/cache/node_modules" 